### ISSUE TITLE
Zero-initial FIPS missing from data?

### ISSUE THREAD

**Issue by b-mohler** [ds5010/vaccines#75]
At least for me, the vaccinations_and_deaths csv files created as a result of running merge don't seem to include any of the counties where the first digit of the FIPS is 0. Those counties are present in the vaccines and deaths files that are created, but are gone once those files have undergone merge. If this is just a problem with my machine I'll just dig into it on my end, but I suspect this is an underlying problem with the merge program we've created in which case we'll need to make an adjustment so we're not losing data. Can someone else take a look at their merge data and confirm one way or the other if this is a problem specific to me, or a larger issue?

**Comment by sophiacofone** [comment]
So I just tested this and I think I am running into the same problem. Could it be because the deaths data doesn't have the leading 0, so once the merge happens it just throws away all the counties like 1007/ 01007 because it thinks that they aren't the same county? If this is the case then could we add a leading 0 when the county code isn't 5 digits for the deaths data to fix?

**Comment by b-mohler** [comment]
Good catch Sophia, that makes sense to me! Presumably we could just use more or less the same code to add a leading 0 to the deaths data that was used for the vaccines data.
