### ISSUE TITLE
Need to decide on intent of the Makefile

### ISSUE THREAD

**Issue by PhilipMathieu** [ds5010/vaccines#92]
This conversation started in #89 . What features do we actually want to have in the Makefile for the final "release"? Should we still have code to download new data?

**Comment by sophiacofone** [comment]
I think I got a little lost in this conversation during class. I think it would be good for reproducibility purposes to show (either an outside user or ourselves at a later date) exactly what we did to download the data. So having a command that does this is good. 

I think we should just be clear what that command is doing (downloading new data that is similar to what we used but not exactly the same) and have a record of the actual data that we used so that our visualizations are backed up. This way a user can download new data if they want, see how we originally downloaded the data, but still see the exact csv's we used at the point in time the visuals were made.

Is this along the lines of what y'all were thinking?

**Comment by PhilipMathieu** [comment]
Closed in class conversation and by #94
