### ISSUE TITLE
Select layout for public-facing GitHub Pages 

### ISSUE THREAD

**Issue by kayneryan** [ds5010/vaccines#96]
In class, we talked about each of us proposing a layout for the GH Pages site. Opening this issue so we can share our ideas and select one.

**Comment by kayneryan** [comment]
Here is my take: https://github.com/ds5010/vaccines/tree/kayne_BootstrappedGHPage/docs

I couldn't do a full screen capture as a static image in Chrome, so I took a quick video. If anyone can tell me how to do that on a Mac, let me know! 

We should be able to nest pages underneath our GH Pages site by creating additional folders in the Docs folder. That will allow us to create a 'deep dive' page for the nationwide analysis and the county vs. county analysis. 

I want the list nav toward the bottom of the page to be sticky--the navigation element on the left should stay anchored while you scroll down the other headers. See the Scrollspy/List-Example component here: https://getbootstrap.com/docs/5.1/components/scrollspy/#example-with-list-group

**Comment by MatthewjRay** [comment]
Awesome, Kayne. Thanks for sharing. I understood it in class as we were each putting together a page for a piece of the Broadband dataset, but I could be wrong.

**Comment by kayneryan** [comment]
Yes I thought we were doing both… just ignore it if I’m wrong. Thanks!

Sent from my iPhone

On Apr 4, 2022, at 9:47 PM, MatthewjRay ***@***.***> wrote:

﻿

Awesome, Kayne. Thanks for sharing. I understood it in class as we were each putting together a page for a piece of the Broadband dataset, but I could be wrong.

**Comment by sophiacofone** [comment]
Really nice! Your website and mine are sort-of similar with some side-by-side content, but I think I like yours better as it is quite clean. Couple of comments: 
1. I think we would want to add a link to the Census Bureau regional divisions
2. I personally think the process part is not really needed for the GH page, and it would be better to just link to the project repository with a small sentence saying something like, "if you want more info on how the data was prepared, etc, please see...." in the Data section. This is definitely an opinion though and others may disagree.
3. I am noticing the buttons don't work, I can imagine you want to link the project repo for the first button, but what would you want to link for the "about the authors",  and "learn more" buttons?

**Comment by MatthewjRay** [comment]
Hi Team. Here is my attempt at creating a Github page for the vaccine data. https://github.com/ds5010/vaccines/find/MatthewjRay-gitpages

I used the Jumbotron template from Bootstrap. I learned a lot and have a few tweaks I would like to continue to work on. Here are a few updates I need/ would like to make. 

- Adding links to data (CDC and JHU)
- Remove the Bootstrap logo in the upper left hand corner of the header
- Play around with the background-color 
- Add a conclusion / next steps section to round out the analysis

**Comment by sophiacofone** [comment]
Hi all, I have the latest iteration of the website ready. Couple of points/things I need help on.
Feedback: 
1. Language/word content. Do we like it? Any sections that need to be more/less detailed?
2. Do we like how the content is organized now? I tried to make it similar to Kanye's with the side by side visuals.
Issues:
1. Nav bar. I tried to do a nav bar similar to what we saw in class, but I couldn't actually find the code from class (so I took it from the bootstrap examples and tried to implement it). The nav bar is sticky, but I can't figure out to get it to scroll to the right sections. Currently all the buttons just bring you back to the top of the page (which we don't want)
2. GitHub link. I somehow broke the GitHub link (with the logo), but I don't know how to fix it, I think because its on the nav bar its just navigating back to the top instead of bringing you to the repo. 

The html code is on my branch [here](https://github.com/ds5010/vaccines/blob/soph_html/docs/index.html).

**Comment by PhilipMathieu** [comment]
I think I can handle the two html issues, but I won't actually look at it until tomorrow night. As long as that's not holding up anything else we should be OK

**Comment by sophiacofone** [comment]
@PhilipMathieu I don’t think it’s holding anything else up, thank you!

**Comment by PhilipMathieu** [comment]
@sophiacofone [Here's the commit with my fixes.](https://github.com/ds5010/vaccines/commit/7d0a2355996ab9448d8a67bd8aae8fbd6bef3f94)
